/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ResultVm
 */
export interface ResultVm {
    /**
     * 
     * @type {string}
     * @memberof ResultVm
     */
    'message'?: string;
    /**
     * 
     * @type {object}
     * @memberof ResultVm
     */
    'data'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof ResultVm
     */
    'success'?: boolean;
}
/**
 * 
 * @export
 * @interface UploadFileRequest
 */
export interface UploadFileRequest {
    /**
     * 
     * @type {File}
     * @memberof UploadFileRequest
     */
    'file': FormData;
}
/**
 * 
 * @export
 * @interface UrlDto
 */
export interface UrlDto {
    /**
     * 
     * @type {string}
     * @memberof UrlDto
     */
    'value'?: string;
}

/**
 * SubmissionControllerApi - axios parameter creator
 * @export
 */
export const SubmissionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Displays the detailed report of the analysis given the Cape Task ID.
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detail: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('detail', 'id', id)
            const localVarPath = `/api/submission/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists completed analyses.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getComplatedSubmissions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/submission/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Displays the screenshots of the analysis given the Cape Task ID.
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        screenshots: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('screenshots', 'id', id)
            const localVarPath = `/api/submission/{id}/screenshots`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubmissionControllerApi - functional programming interface
 * @export
 */
export const SubmissionControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubmissionControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Displays the detailed report of the analysis given the Cape Task ID.
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async detail(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.detail(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmissionControllerApi.detail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Lists completed analyses.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getComplatedSubmissions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getComplatedSubmissions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmissionControllerApi.getComplatedSubmissions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Displays the screenshots of the analysis given the Cape Task ID.
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async screenshots(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.screenshots(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmissionControllerApi.screenshots']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubmissionControllerApi - factory interface
 * @export
 */
export const SubmissionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubmissionControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Displays the detailed report of the analysis given the Cape Task ID.
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detail(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.detail(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists completed analyses.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getComplatedSubmissions(options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.getComplatedSubmissions(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Displays the screenshots of the analysis given the Cape Task ID.
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        screenshots(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.screenshots(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * uploadFile - object-oriented interface
 * @export
 * @class SubmissionControllerApi
 * @extends {BaseAPI}
 */
export class SubmissionControllerApi extends BaseAPI {
    /**
     * 
     * @summary Displays the detailed report of the analysis given the Cape Task ID.
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmissionControllerApi
     */
    public detail(id: number, options?: RawAxiosRequestConfig) {
        return SubmissionControllerApiFp(this.configuration).detail(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Lists completed analyses.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmissionControllerApi
     */
    public getComplatedSubmissions(options?: RawAxiosRequestConfig) {
        return SubmissionControllerApiFp(this.configuration).getComplatedSubmissions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Displays the screenshots of the analysis given the Cape Task ID.
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmissionControllerApi
     */
    public screenshots(id: number, options?: RawAxiosRequestConfig) {
        return SubmissionControllerApiFp(this.configuration).screenshots(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SubmitControllerApi - axios parameter creator
 * @export
 */
export const SubmitControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Checks whether the same file has been sent before.
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controlFile: async (uploadFileRequest?: UploadFileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/submit/controlFile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadFileRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit a URL task to be analyzed by Tamu Sandbox. Return object will be JSON.
         * @param {string} url 
         * @param {string} machine 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitUrl: async (url: string, machine: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'url' is not null or undefined
            assertParamExists('submitUrl', 'url', url)
            // verify required parameter 'machine' is not null or undefined
            assertParamExists('submitUrl', 'machine', machine)
            const localVarPath = `/api/submit/url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (url !== undefined) {
                localVarQueryParameter['url'] = url;
            }

            if (machine !== undefined) {
                localVarQueryParameter['machine'] = machine;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit a file task to be analyzed by Tamu Sandbox. Return object will be JSON.
         * @param {string} machine 
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile: async (machine: string, uploadFileRequest?: UploadFileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'machine' is not null or undefined
            assertParamExists('uploadFile', 'machine', machine)
            const localVarPath = `/api/submit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (machine !== undefined) {
                localVarQueryParameter['machine'] = machine;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadFileRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit a file to try static extractors on it, file won\'t be submited to Virtual Machine. Return object will be JSON.
         * @param {string} machine 
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileForStaticAnalyze: async (machine: string, uploadFileRequest?: UploadFileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'machine' is not null or undefined
            assertParamExists('uploadFileForStaticAnalyze', 'machine', machine)
            const localVarPath = `/api/submit/staticAnalyze`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (machine !== undefined) {
                localVarQueryParameter['machine'] = machine;
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadFileRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary You can send the URL to perform dynamic analysis of files located on a remote server or computer.
         * @param {UrlDto} urlDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFromUrl: async (urlDto: UrlDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'urlDto' is not null or undefined
            assertParamExists('uploadFromUrl', 'urlDto', urlDto)
            const localVarPath = `/api/submit/uploadFromUrl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(urlDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubmitControllerApi - functional programming interface
 * @export
 */
export const SubmitControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubmitControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Checks whether the same file has been sent before.
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async controlFile(uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.controlFile(uploadFileRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmitControllerApi.controlFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Submit a URL task to be analyzed by Tamu Sandbox. Return object will be JSON.
         * @param {string} url 
         * @param {string} machine 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitUrl(url: string, machine: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitUrl(url, machine, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmitControllerApi.submitUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Submit a file task to be analyzed by Tamu Sandbox. Return object will be JSON.
         * @param {string} machine 
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFile(machine: string, uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFile(machine, uploadFileRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmitControllerApi.uploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Submit a file to try static extractors on it, file won\'t be submited to Virtual Machine. Return object will be JSON.
         * @param {string} machine 
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileForStaticAnalyze(machine: string, uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFileForStaticAnalyze(machine, uploadFileRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmitControllerApi.uploadFileForStaticAnalyze']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary You can send the URL to perform dynamic analysis of files located on a remote server or computer.
         * @param {UrlDto} urlDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFromUrl(urlDto: UrlDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFromUrl(urlDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubmitControllerApi.uploadFromUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubmitControllerApi - factory interface
 * @export
 */
export const SubmitControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubmitControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Checks whether the same file has been sent before.
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        controlFile(uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.controlFile(uploadFileRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Submit a URL task to be analyzed by Tamu Sandbox. Return object will be JSON.
         * @param {string} url 
         * @param {string} machine 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitUrl(url: string, machine: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.submitUrl(url, machine, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Submit a file task to be analyzed by Tamu Sandbox. Return object will be JSON.
         * @param {string} machine 
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile(machine: string, uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.uploadFile(machine, uploadFileRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Submit a file to try static extractors on it, file won\'t be submited to Virtual Machine. Return object will be JSON.
         * @param {string} machine 
         * @param {UploadFileRequest} [uploadFileRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileForStaticAnalyze(machine: string, uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.uploadFileForStaticAnalyze(machine, uploadFileRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary You can send the URL to perform dynamic analysis of files located on a remote server or computer.
         * @param {UrlDto} urlDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFromUrl(urlDto: UrlDto, options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.uploadFromUrl(urlDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubmitControllerApi - object-oriented interface
 * @export
 * @class SubmitControllerApi
 * @extends {BaseAPI}
 */
export class SubmitControllerApi extends BaseAPI {
    /**
     * 
     * @summary Checks whether the same file has been sent before.
     * @param {UploadFileRequest} [uploadFileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmitControllerApi
     */
    public controlFile(uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig) {
        return SubmitControllerApiFp(this.configuration).controlFile(uploadFileRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Submit a URL task to be analyzed by Tamu Sandbox. Return object will be JSON.
     * @param {string} url 
     * @param {string} machine 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmitControllerApi
     */
    public submitUrl(url: string, machine: string, options?: RawAxiosRequestConfig) {
        return SubmitControllerApiFp(this.configuration).submitUrl(url, machine, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Submit a file task to be analyzed by Tamu Sandbox. Return object will be JSON.
     * @param {string} machine 
     * @param {UploadFileRequest} [uploadFileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmitControllerApi
     */
    public uploadFile(machine: string, uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig) {
        return SubmitControllerApiFp(this.configuration).uploadFile(machine, uploadFileRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Submit a file to try static extractors on it, file won\'t be submited to Virtual Machine. Return object will be JSON.
     * @param {string} machine 
     * @param {UploadFileRequest} [uploadFileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmitControllerApi
     */
    public uploadFileForStaticAnalyze(machine: string, uploadFileRequest?: UploadFileRequest, options?: RawAxiosRequestConfig) {
        return SubmitControllerApiFp(this.configuration).uploadFileForStaticAnalyze(machine, uploadFileRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary You can send the URL to perform dynamic analysis of files located on a remote server or computer.
     * @param {UrlDto} urlDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmitControllerApi
     */
    public uploadFromUrl(urlDto: UrlDto, options?: RawAxiosRequestConfig) {
        return SubmitControllerApiFp(this.configuration).uploadFromUrl(urlDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SyncControllerApi - axios parameter creator
 * @export
 */
export const SyncControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sycncCapeAndTamu: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sync/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sycncReports: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sync/reports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncDowloadScreenShots: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sync/syncScreenShots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SyncControllerApi - functional programming interface
 * @export
 */
export const SyncControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SyncControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sycncCapeAndTamu(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sycncCapeAndTamu(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncControllerApi.sycncCapeAndTamu']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sycncReports(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sycncReports(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncControllerApi.sycncReports']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncDowloadScreenShots(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncDowloadScreenShots(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SyncControllerApi.syncDowloadScreenShots']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SyncControllerApi - factory interface
 * @export
 */
export const SyncControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SyncControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sycncCapeAndTamu(options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.sycncCapeAndTamu(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sycncReports(options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.sycncReports(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncDowloadScreenShots(options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.syncDowloadScreenShots(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SyncControllerApi - object-oriented interface
 * @export
 * @class SyncControllerApi
 * @extends {BaseAPI}
 */
export class SyncControllerApi extends BaseAPI {
    /**
     * 
     * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncControllerApi
     */
    public sycncCapeAndTamu(options?: RawAxiosRequestConfig) {
        return SyncControllerApiFp(this.configuration).sycncCapeAndTamu(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncControllerApi
     */
    public sycncReports(options?: RawAxiosRequestConfig) {
        return SyncControllerApiFp(this.configuration).sycncReports(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary DONT USE! It is used to synchronize Cape with Tamu Sandbox. It should only be used by the system administrator.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyncControllerApi
     */
    public syncDowloadScreenShots(options?: RawAxiosRequestConfig) {
        return SyncControllerApiFp(this.configuration).syncDowloadScreenShots(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VirtualMachineControllerApi - axios parameter creator
 * @export
 */
export const VirtualMachineControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Lists Virtual Machines.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMachines: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/vm/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VirtualMachineControllerApi - functional programming interface
 * @export
 */
export const VirtualMachineControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VirtualMachineControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Lists Virtual Machines.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMachines(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultVm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMachines(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VirtualMachineControllerApi.getMachines']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VirtualMachineControllerApi - factory interface
 * @export
 */
export const VirtualMachineControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VirtualMachineControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Lists Virtual Machines.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMachines(options?: RawAxiosRequestConfig): AxiosPromise<ResultVm> {
            return localVarFp.getMachines(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VirtualMachineControllerApi - object-oriented interface
 * @export
 * @class VirtualMachineControllerApi
 * @extends {BaseAPI}
 */
export class VirtualMachineControllerApi extends BaseAPI {
    /**
     * 
     * @summary Lists Virtual Machines.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VirtualMachineControllerApgi
     */
    public getMachines(options?: RawAxiosRequestConfig) {
        return VirtualMachineControllerApiFp(this.configuration).getMachines(options).then((request) => request(this.axios, this.basePath));
    }
}



